title: extazystas.ru
author:
  name: Stanislav Knyazev
  email: extazystas@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Stanislav Knyazev personal developer's blog about programming in ruby, javascript and so on. Contains of useful tips not to forget.
baseurl: "" # the subpath of your site, e.g. /blog
github_username: extazystas

markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
permalink: /articles/:year/:month/:title
timezone: Europe/Minsk
excerpt_separator: <!--more-->  # you can specify your own separator, of course.
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'UploadToGithub.Rakefile', 'README.md', 'CNAME']
safe: false
post:
  template: _post.txt
  extension: md
git:
  branch: master
# transfer:
#   command: rsync
#   settings: -av
#   source: _site/
#   destination: ~/Git/extazystas.github.com/
plugins: [jekyll-paginate, github-pages]

# Build settings
plugins_dir:
  - jekyll-paginate
  - github-pages
exclude:
  - Gemfile
  - Gemfile.lock
paginate: 7
paginate_path: '/page/:num/'
# pagination:
#   enabled: true
#   per_page: 5
#   offset: 2
  # permalink: '/page/:num/'
#   title: ':title - page :num of :max'
#   limit: 0
#   sort_field: 'date'
#   sort_reverse: true
